---
- name: Remove IPsec connection configs
  file:
    path: "{{ network_encryption_config_dir }}/\
      {{ network_encryption_config.name }}-{{ connection.local.hostname }}-to-{{ connection.remote.hostname }}.conf"
    state: absent
  with_items: "{{ network_encryption_absent_connections }}"
  loop_control:
    loop_var: connection
  notify: reload ipsec

- name: Add IPsec connection configs
  template:
    src: templates/ipsec.conf.j2
    dest: "{{ network_encryption_config_dir }}/\
      {{ network_encryption_config.name }}-{{ connection.local.hostname }}-to-{{ connection.remote.hostname }}.conf"
  with_items: "{{ network_encryption_connections }}"
  loop_control:
    loop_var: connection
  notify: reload ipsec