---
- name: Install required packages
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ network_encryption_packages }}"

- name: Ensure IPsec service is started
  service:
    name: "{{ network_encryption_ipsec_service_name }}"
    enabled: yes
    state: started
