---
- name: Gather OS specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_distribution|lower }}_{{ ansible_distribution_major_version }}.yml"
        - "default.yml"
      paths:
        - ../vars
  tags: ['network_encryption', 'network_encryption_variables', 'variables']
  when: network_encryption_host_configs is defined and (network_encryption_host_configs | length > 0)

- name: Install strongSwan
  include: install.yml
  tags: ['network_encryption', 'network_encryption_install', 'install']
  when: network_encryption_host_configs is defined and (network_encryption_host_configs | length > 0)

- name: Configure strongSwan
  include: config/main.yml
  tags: ['network_encryption', 'network_encryption_config', 'config']
  when: network_encryption_host_configs is defined and (network_encryption_host_configs | length > 0)
