---
- name: Remove IPsec secrets template
  file:
    path: "{{ ipsec_secrets_file_path }}"
    state: absent
  when: inventory_hostname in network_encryption_config.absent_hosts
  notify: reload ipsec