---
- name: Remove IPsec secrets config
  include_tasks: delete.yml
  when: inventory_hostname in network_encryption_config.absent_hosts

- name: Add IPsec secrets template
  include_tasks: create.yml
  when: inventory_hostname in network_encryption_config.hosts
