---
- name: Prepare hosts
  hosts: all
  tasks:
    - name: Install required packages
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - kmod

- name: Prepare controller
  hosts: localhost
  tasks:
    - name: Install ansible-filter package
      pip:
        name: ansible-filter==1.0.0