---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: one
    image: ubuntu:16.04
    dockerfile: ../resources/playbooks/Dockerfile.j2
  - name: two
    image: ubuntu:16.04
    dockerfile: ../resources/playbooks/Dockerfile.j2
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  playbooks:
    converge: ../resources/playbooks/playbook.yml
    verify: ../resources/playbooks/verify/noop.yml
verifier:
  name: ansible
  lint:
    name: ansible-lint
