---
- name: Set interface
  set_fact:
    network_encryption_config_interface: "{{ network_encryption_config.interface | default(None) }}"

- name: Resolve connections
  set_fact:
    network_encryption_connections: "{{ \
      network_encryption_config.hosts \
      | network_encryption_point_to_point_connections(inventory_hostname, hostvars, network_encryption_config_interface)\
    }}"
    network_encryption_absent_connections: "{{ \
      network_encryption_config.absent_hosts \
      | network_encryption_point_to_point_connections(inventory_hostname, hostvars, network_encryption_config_interface)\
    }}"
    network_encryption_absent_all_connections: "{{ \
      network_encryption_config.hosts + network_encryption_config.absent_hosts \
      | network_encryption_point_to_point_connections(inventory_hostname, hostvars, network_encryption_config_interface)\
    }}"
    network_encryption_connection_params: "{{ \
      network_encryption_default_connection_params \
      | combine(network_encryption_config.params | default({})) \
    }}"

- name: Set IPsec secrets file path
  set_fact:
    ipsec_secrets_file_path: "{{ network_encryption_config_dir }}/{{ network_encryption_config.name }}.secrets"

- name: Configure IPsec secrets
  include_tasks: secret/main.yml

- name: Configure IPsec secrets
  include_tasks: connection/main.yml
